"""Add User model and add user_id to Document

Revision ID: 4667b14d4ca3
Revises: 000000000001
Create Date: 2025-12-13 15:18:52.168086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4667b14d4ca3'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('documents', sa.Column('doc_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('idx_doc_id', table_name='documents')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_index('idx_doc_id', 'documents', ['doc_id'], unique=False)
    op.drop_column('documents', 'user_id')
    op.drop_column('documents', 'doc_type')
    op.drop_table('users')
    # ### end Alembic commands ###
